
import 'dart:convert';
import 'dart:io';

void main() {
  final zhFile = File('assets/i18n/zh.json');
  final enFile = File('assets/i18n/en.json');

  final missingKeys = [
    "blocks.afternoon.color", "blocks.afternoon.emoji", "blocks.afternoon.name",
    "blocks.evening.color", "blocks.evening.emoji", "blocks.evening.name",
    "blocks.morning.color", "blocks.morning.emoji", "blocks.morning.name",
    "common.cancel", "common.dayToday", "common.dayTomorrow", "common.ignore", "common.save",
    "greeting", "screens.pomodoro.bindTask", "screens.pomodoro.currentPhase",
    "screens.pomodoro.cycle", "screens.pomodoro.cycleUnit", "screens.pomodoro.focus",
    "screens.pomodoro.longBreak", "screens.pomodoro.nextPhase", "screens.pomodoro.noTask",
    "screens.pomodoro.pause", "screens.pomodoro.reset", "screens.pomodoro.resume",
    "screens.pomodoro.shortBreak", "screens.pomodoro.skip", "screens.pomodoro.start",
    "screens.settings.appNameLbl", "screens.settings.applyThemeWithName", "screens.settings.changeWallpaper",
    "screens.settings.colorModeTip", "screens.settings.colorThresh", "screens.settings.completed",
    "screens.settings.current", "screens.settings.currentPreview", "screens.settings.customAppCategories",
    "screens.settings.customBgImage", "screens.settings.customBgImageHint", "screens.settings.customCategoriesSet",
    "screens.settings.defaultStatsViewSubtitle", "screens.settings.defaultView", "screens.settings.disposable",
    "screens.settings.festivalCalendarHint", "screens.settings.globalAppearance", "screens.settings.globalBgColor",
    "screens.settings.globalBgColorHintImage", "screens.settings.globalBgColorHintNoImage",
    "screens.settings.globalOpacityHintImage", "screens.settings.globalOpacityHintNoImage",
    "screens.settings.installDate", "screens.settings.logs.action", "screens.settings.logs.all",
    "screens.settings.logs.clearConfirmContent", "screens.settings.logs.clearConfirmTitle",
    "screens.settings.logs.clearLogs", "screens.settings.logs.copiedOne", "screens.settings.logs.copyReport",
    "screens.settings.logs.copySuccess", "screens.settings.logs.emptyNoLogs", "screens.settings.logs.emptyNoMatch",
    "screens.settings.logs.entriesCount", "screens.settings.logs.error", "screens.settings.logs.exportShare",
    "screens.settings.logs.fatal", "screens.settings.logs.info", "screens.settings.logs.searchHint",
    "screens.settings.logs.shareFailed", "screens.settings.logs.sortNewestFirst", "screens.settings.logs.sortOldestFirst",
    "screens.settings.logs.summaryAction", "screens.settings.logs.summaryError", "screens.settings.logs.summaryTotal",
    "screens.settings.logs.summaryWarn", "screens.settings.logs.title", "screens.settings.logs.warn",
    "screens.settings.longPresEdit", "screens.settings.monthlyReport", "screens.settings.monthlyReportSubject",
    "screens.settings.monthlyReportSubtitle", "screens.settings.moreExportOptions", "screens.settings.moreExportOptionsDesc",
    "screens.settings.openingGallery", "screens.settings.rate", "screens.settings.restoreDefaultBg",
    "screens.settings.semSettings", "screens.settings.showPomodoro", "screens.settings.tagMgmt",
    "screens.settings.topChromeOpacityHint", "screens.settings.topChromeOpacityTitle", "screens.settings.total",
    "screens.settings.uploadWallpaper", "screens.settings.wallpaperModeTip", "screens.settings.wallpaperUploadHint",
    "screens.settings.weeklyReport", "screens.settings.weeklyReportSubject", "screens.settings.weeklyReportSubtitle",
    "screens.stats.actual", "screens.stats.actualDoneCount", "screens.stats.afternoon", "screens.stats.alphaLabel",
    "screens.stats.countLabel", "screens.stats.day", "screens.stats.deviationDesc", "screens.stats.deviationTitle",
    "screens.stats.evening", "screens.stats.morning", "screens.stats.noData", "screens.stats.onTimeRate",
    "screens.stats.planned", "screens.stats.plannedCount", "screens.stats.rankLabel", "screens.stats.timeLabel",
    "screens.stats.vitalityTitle", "screens.statsNew.afternoon", "screens.statsNew.bento.appUsageDuration",
    "screens.statsNew.bento.behavioralInsights", "screens.statsNew.bento.categoryGame", "screens.statsNew.bento.categoryLegendItem",
    "screens.statsNew.bento.categoryMusic", "screens.statsNew.bento.categoryNews", "screens.statsNew.bento.categorySocial",
    "screens.statsNew.bento.categoryVideo", "screens.statsNew.bento.categoryWork", "screens.statsNew.bento.cognitivePattern",
    "screens.statsNew.bento.completionTime", "screens.statsNew.bento.completionTimeDistribution", "screens.statsNew.bento.createdAt",
    "screens.statsNew.bento.deviationAhead", "screens.statsNew.bento.deviationDelayed", "screens.statsNew.bento.deviationNoData",
    "screens.statsNew.bento.deviationOnTime", "screens.statsNew.bento.efficiencyHealthIndex", "screens.statsNew.bento.estimateDeviation",
    "screens.statsNew.bento.flowAutoRecordedHint", "screens.statsNew.bento.flowCompletePomHint", "screens.statsNew.bento.flowImproveTitle",
    "screens.statsNew.bento.flowScoreUnit", "screens.statsNew.bento.flowTip1Body", "screens.statsNew.bento.flowTip1Title",
    "screens.statsNew.bento.flowTip2Body", "screens.statsNew.bento.flowTip2Title", "screens.statsNew.bento.flowTip3Body",
    "screens.statsNew.bento.flowTip3Title", "screens.statsNew.bento.flowTip4Body", "screens.statsNew.bento.flowTip4Title",
    "screens.statsNew.bento.flowTrend30Days", "screens.statsNew.bento.flowWhatIsBody", "screens.statsNew.bento.flowWhatIsTitle",
    "screens.statsNew.bento.focusEntertainmentSummary", "screens.statsNew.bento.habitBrickHint", "screens.statsNew.bento.habitCountLabel",
    "screens.statsNew.bento.habitPageHint", "screens.statsNew.bento.habitStrengthBuilding", "screens.statsNew.bento.habitStrengthStable",
    "screens.statsNew.bento.habitStrengthStarting", "screens.statsNew.bento.habitStrengthSuper", "screens.statsNew.bento.habitTracking",
    "screens.statsNew.bento.hourlyCompletionDistribution", "screens.statsNew.bento.ignorePeriodCount", "screens.statsNew.bento.ignoreRate",
    "screens.statsNew.bento.ignoreTitle", "screens.statsNew.bento.ignoreTotal", "screens.statsNew.bento.ignoredByTag",
    "screens.statsNew.bento.ignoredTasksCancelable", "screens.statsNew.bento.last14DaysCompletion", "screens.statsNew.bento.last30Days",
    "screens.statsNew.bento.loading", "screens.statsNew.bento.noFlowRecords", "screens.statsNew.bento.noHabitsSubtitle",
    "screens.statsNew.bento.noHabitsTitle", "screens.statsNew.bento.noIgnoredTasks", "screens.statsNew.bento.peakHour",
    "screens.statsNew.bento.peakHourLabel", "screens.statsNew.bento.plannedVsActualBlocks", "screens.statsNew.bento.procrastinationHigh",
    "screens.statsNew.bento.procrastinationIndex", "screens.statsNew.bento.procrastinationLow", "screens.statsNew.bento.procrastinationMid",
    "screens.statsNew.bento.procrastinationTendencyIndex", "screens.statsNew.bento.psychDisclaimer", "screens.statsNew.bento.psychologyAnalysis",
    "screens.statsNew.bento.psychologyReport", "screens.statsNew.bento.restore", "screens.statsNew.bento.screenTaskCrossInsights",
    "screens.statsNew.bento.statusAdjust", "screens.statsNew.bento.statusGood", "screens.statsNew.bento.statusImprove",
    "screens.statsNew.bento.streak", "screens.statsNew.bento.streak7DaysPlus", "screens.statsNew.bento.tapToGrantPermission",
    "screens.statsNew.bento.targetedImprovements", "screens.statsNew.bento.timesPerWeek", "screens.statsNew.bento.todayAppCategoryUsage",
    "screens.statsNew.bento.todayDone", "screens.statsNew.bento.todayTodo", "screens.statsNew.bento.unignoreHint",
    "screens.statsNew.bento.unignoredSnack", "screens.statsNew.bento.usageAnalysis", "screens.statsNew.bento.usageAnalysisBeta",
    "screens.statsNew.bestVitality", "screens.statsNew.completedTasks", "screens.statsNew.completionDistribution",
    "screens.statsNew.completionRank", "screens.statsNew.completionRateByBlock", "screens.statsNew.completionTitle",
    "screens.statsNew.dailyCompletion", "screens.statsNew.dailyFocusDuration", "screens.statsNew.dateFormat",
    "screens.statsNew.dayOfYear", "screens.statsNew.deviation", "screens.statsNew.evening", "screens.statsNew.focus",
    "screens.statsNew.focusStats", "screens.statsNew.monthFormat", "screens.statsNew.morning", "screens.statsNew.noData",
    "screens.statsNew.noDeviationData", "screens.statsNew.noise.assess.loud", "screens.statsNew.noise.assess.moderate",
    "screens.statsNew.noise.assess.quiet", "screens.statsNew.noise.assess.silent", "screens.statsNew.noise.assess.veryLoud",
    "screens.statsNew.noise.avgDbDashLabel", "screens.statsNew.noise.avgDbLabel", "screens.statsNew.noise.bestFocusTime",
    "screens.statsNew.noise.envFocus30Days", "screens.statsNew.noise.envGood", "screens.statsNew.noise.envNoisy",
    "screens.statsNew.noise.envScoreSummary", "screens.statsNew.noise.history", "screens.statsNew.noise.latestDb",
    "screens.statsNew.noise.level.loud", "screens.statsNew.noise.level.moderate", "screens.statsNew.noise.level.quiet",
    "screens.statsNew.noise.level.silent", "screens.statsNew.noise.level.veryLoud", "screens.statsNew.noise.manualMeasure",
    "screens.statsNew.noise.noHistory", "screens.statsNew.noise.personalAdvice", "screens.statsNew.noise.pomSampling",
    "screens.statsNew.noise.pomTrend", "screens.statsNew.noise.recording", "screens.statsNew.noise.samplesLine",
    "screens.statsNew.noise.secondsProgress", "screens.statsNew.noise.singleSession", "screens.statsNew.noise.start30s",
    "screens.statsNew.noise.suggestBasedOnMedian", "screens.statsNew.noise.suggestFocusMins", "screens.statsNew.noise.tapRecordHint",
    "screens.statsNew.noise.tapToRecord", "screens.statsNew.noise.title", "screens.statsNew.noise.waiting",
    "screens.statsNew.noise.yModerate", "screens.statsNew.noise.yNoisy", "screens.statsNew.noise.yQuiet",
    "screens.statsNew.onTime", "screens.statsNew.overallAdvanced", "screens.statsNew.overallDelayed",
    "screens.statsNew.periodAdded", "screens.statsNew.periodCompleted", "screens.statsNew.periodCompletion",
    "screens.statsNew.periodFocus", "screens.statsNew.plannedVsActual", "screens.statsNew.semesterWeek",
    "screens.statsNew.share", "screens.statsNew.tagCompletion", "screens.statsNew.tagDetails",
    "screens.statsNew.tagFocusRank", "screens.statsNew.tagStats", "screens.statsNew.tagStatsHeader",
    "screens.statsNew.tagTotalCompletion", "screens.statsNew.timeBlockDistribution", "screens.statsNew.totalCompleted",
    "screens.statsNew.totalFocus", "screens.statsNew.vitalitySummary", "screens.statsNew.weekFormat",
    "screens.statsNew.weekRange", "screens.statsNew.yearFormat", "screens.today.noTasks",
    "screens.today.presets.beige", "screens.today.presets.darkBlue", "screens.today.presets.darkGray",
    "screens.today.presets.darkGreen", "screens.today.presets.lightBlue", "screens.today.presets.lightGreen",
    "screens.today.presets.lightPink", "screens.today.presets.lightPurple", "screens.today.presets.limestone",
    "screens.today.presets.warmWhite", "screens.today.smartPlan.psych.cognitiveInsight.burstStall",
    "screens.today.smartPlan.psych.cognitiveInsight.fluctuating", "screens.today.smartPlan.psych.cognitiveInsight.lowStart",
    "screens.today.smartPlan.psych.cognitiveInsight.stable", "screens.today.smartPlan.psych.deepFocus.insufficientInsight",
    "screens.today.smartPlan.psych.ignoreRateInsight", "screens.today.smartPlan.psych.procrastination.highInsight",
    "screens.today.smartPlan.psych.procrastination.lowInsight", "screens.today.smartPlan.psych.procrastination.midInsight",
    "screens.today.smartPlan.psych.recommendations.alignWithGoals", "screens.today.smartPlan.psych.recommendations.minExecutionBaseline",
    "screens.today.smartPlan.psych.recommendations.scheduleHardInPeak", "screens.today.smartPlan.psych.recommendations.singleTaskFocus",
    "screens.today.smartPlan.psych.recommendations.splitOverdue", "screens.today.smartPlan.psych.recommendations.twoMinuteRule",
    "screens.today.smartPlan.psych.selfEfficacy.low", "screens.today.todayFocus", "time.hourMinute"
  ];

  Map<String, String> zhMap = {
    "blocks.afternoon.color": "下午颜色",
    "blocks.afternoon.emoji": "☀️",
    "blocks.afternoon.name": "下午",
    "blocks.evening.color": "晚上颜色",
    "blocks.evening.emoji": "🌙",
    "blocks.evening.name": "晚上",
    "blocks.morning.color": "早晨颜色",
    "blocks.morning.emoji": "🌅",
    "blocks.morning.name": "早晨",
    "common.cancel": "取消",
    "common.dayToday": "今日",
    "common.dayTomorrow": "明日",
    "common.ignore": "忽略",
    "common.save": "保存",
    "greeting": "你好",
    "screens.pomodoro.bindTask": "绑定任务",
    "screens.pomodoro.currentPhase": "当前阶段",
    "screens.pomodoro.cycle": "循环",
    "screens.pomodoro.cycleUnit": "次",
    "screens.pomodoro.focus": "专注",
    "screens.pomodoro.longBreak": "长休",
    "screens.pomodoro.nextPhase": "下一阶段",
    "screens.pomodoro.noTask": "无任务",
    "screens.pomodoro.pause": "暂停",
    "screens.pomodoro.reset": "重置",
    "screens.pomodoro.resume": "继续",
    "screens.pomodoro.shortBreak": "短休",
    "screens.pomodoro.skip": "跳过",
    "screens.pomodoro.start": "开始",
    "screens.settings.appNameLbl": "应用名称",
    "screens.settings.applyThemeWithName": "应用主题：{{name}}",
    "screens.settings.changeWallpaper": "更换壁纸",
    "screens.settings.colorModeTip": "颜色模式提示",
    "screens.settings.colorThresh": "颜色阈值",
    "screens.settings.completed": "已完成",
    "screens.settings.current": "当前",
    "screens.settings.currentPreview": "当前预览",
    "screens.settings.customAppCategories": "自定义应用分类",
    "screens.settings.customBgImage": "自定义背景图片",
    "screens.settings.customBgImageHint": "点击上传背景图片",
    "screens.settings.customCategoriesSet": "已设置自定义分类",
    "screens.settings.defaultStatsViewSubtitle": "统计页默认显示的视图",
    "screens.settings.defaultView": "默认视图",
    "screens.settings.disposable": "可用时间",
    "screens.settings.festivalCalendarHint": "显示节日日历",
    "screens.settings.globalAppearance": "全局外观",
    "screens.settings.globalBgColor": "全局背景颜色",
    "screens.settings.globalBgColorHintImage": "背景图片透明度",
    "screens.settings.globalBgColorHintNoImage": "背景颜色",
    "screens.settings.globalOpacityHintImage": "全局不透明度（含图片）",
    "screens.settings.globalOpacityHintNoImage": "全局不透明度",
    "screens.settings.installDate": "安装日期",
    "screens.settings.logs.action": "操作",
    "screens.settings.logs.all": "全部日志",
    "screens.settings.logs.clearConfirmContent": "确定要清除所有日志吗？",
    "screens.settings.logs.clearConfirmTitle": "清除日志",
    "screens.settings.logs.clearLogs": "清除",
    "screens.settings.logs.copiedOne": "已复制一条日志",
    "screens.settings.logs.copyReport": "复制报告",
    "screens.settings.logs.copySuccess": "复制成功",
    "screens.settings.logs.emptyNoLogs": "暂无日志",
    "screens.settings.logs.emptyNoMatch": "未找到匹配日志",
    "screens.settings.logs.entriesCount": "共 {{count}} 条记录",
    "screens.settings.logs.error": "错误",
    "screens.settings.logs.exportShare": "导出分享",
    "screens.settings.logs.fatal": "致命",
    "screens.settings.logs.info": "信息",
    "screens.settings.logs.searchHint": "搜索日志内容...",
    "screens.settings.logs.shareFailed": "分享失败",
    "screens.settings.logs.sortNewestFirst": "时间倒序",
    "screens.settings.logs.sortOldestFirst": "时间正序",
    "screens.settings.logs.summaryAction": "操作",
    "screens.settings.logs.summaryError": "错误",
    "screens.settings.logs.summaryTotal": "总计",
    "screens.settings.logs.summaryWarn": "警告",
    "screens.settings.logs.title": "诊断日志",
    "screens.settings.logs.warn": "警告",
    "screens.settings.longPresEdit": "长按编辑",
    "screens.settings.monthlyReport": "月度报告",
    "screens.settings.monthlyReportSubject": "流水账月度报告",
    "screens.settings.monthlyReportSubtitle": "每月 1 日生成的月度分析",
    "screens.settings.moreExportOptions": "更多导出选项",
    "screens.settings.moreExportOptionsDesc": "支持 JSON, CSV 等格式导出",
    "screens.settings.openingGallery": "正在打开相册...",
    "screens.settings.rate": "评分",
    "screens.settings.restoreDefaultBg": "还原默认背景",
    "screens.settings.semSettings": "学期设置",
    "screens.settings.showPomodoro": "显示番茄钟",
    "screens.settings.tagMgmt": "标签管理",
    "screens.settings.topChromeOpacityHint": "顶部状态栏不透明度",
    "screens.settings.topChromeOpacityTitle": "顶部透明度",
    "screens.settings.total": "总计",
    "screens.settings.uploadWallpaper": "上传壁纸",
    "screens.settings.wallpaperModeTip": "壁纸模式提示",
    "screens.settings.wallpaperUploadHint": "点击上传新壁纸",
    "screens.settings.weeklyReport": "每周报告",
    "screens.settings.weeklyReportSubject": "流水账每周报告",
    "screens.settings.weeklyReportSubtitle": "每周一生成的周度分析",
    "screens.stats.actual": "实际",
    "screens.stats.actualDoneCount": "实际完成：{{count}}",
    "screens.stats.afternoon": "下午",
    "screens.stats.alphaLabel": "字母",
    "screens.stats.countLabel": "数量",
    "screens.stats.day": "日",
    "screens.stats.deviationDesc": "预估时间与实际完成的偏差分析",
    "screens.stats.deviationTitle": "偏差分析",
    "screens.stats.evening": "晚上",
    "screens.stats.morning": "早晨",
    "screens.stats.noData": "暂无数据",
    "screens.stats.onTimeRate": "准时率",
    "screens.stats.planned": "计划",
    "screens.stats.plannedCount": "计划任务：{{count}}",
    "screens.stats.rankLabel": "排名",
    "screens.stats.timeLabel": "时长",
    "screens.stats.vitalityTitle": "活力统计",
    "screens.statsNew.afternoon": "下午",
    "screens.statsNew.bento.appUsageDuration": "App 使用时长",
    "screens.statsNew.bento.behavioralInsights": "行为洞察",
    "screens.statsNew.bento.categoryGame": "游戏",
    "screens.statsNew.bento.categoryLegendItem": "分类图例",
    "screens.statsNew.bento.categoryMusic": "音乐",
    "screens.statsNew.bento.categoryNews": "新闻",
    "screens.statsNew.bento.categorySocial": "社交",
    "screens.statsNew.bento.categoryVideo": "视频",
    "screens.statsNew.bento.categoryWork": "工作",
    "screens.statsNew.bento.cognitivePattern": "认知模式",
    "screens.statsNew.bento.completionTime": "完成时间",
    "screens.statsNew.bento.completionTimeDistribution": "完成时间分布",
    "screens.statsNew.bento.createdAt": "创建于",
    "screens.statsNew.bento.deviationAhead": "提前",
    "screens.statsNew.bento.deviationDelayed": "延后",
    "screens.statsNew.bento.deviationNoData": "无偏差数据",
    "screens.statsNew.bento.deviationOnTime": "准时",
    "screens.statsNew.bento.efficiencyHealthIndex": "效率健康指数",
    "screens.statsNew.bento.estimateDeviation": "预估偏差",
    "screens.statsNew.bento.flowAutoRecordedHint": "心流由番茄钟自动记录",
    "screens.statsNew.bento.flowCompletePomHint": "完成番茄钟以产生心流记录",
    "screens.statsNew.bento.flowImproveTitle": "心流提升建议",
    "screens.statsNew.bento.flowScoreUnit": "分",
    "screens.statsNew.bento.flowTip1Body": "选择合适的挑战难度",
    "screens.statsNew.bento.flowTip1Title": "匹配技能",
    "screens.statsNew.bento.flowTip2Body": "减少外界干扰",
    "screens.statsNew.bento.flowTip2Title": "环境控制",
    "screens.statsNew.bento.flowTip3Body": "设定明确的目标",
    "screens.statsNew.bento.flowTip3Title": "清晰目标",
    "screens.statsNew.bento.flowTip4Body": "关注即时反馈",
    "screens.statsNew.bento.flowTip4Title": "即时反馈",
    "screens.statsNew.bento.flowTrend30Days": "近30日心流趋势",
    "screens.statsNew.bento.flowWhatIsBody": "心流是一种全身心投入的状态",
    "screens.statsNew.bento.flowWhatIsTitle": "什么是心流？",
    "screens.statsNew.bento.focusEntertainmentSummary": "专注与娱乐概览",
    "screens.statsNew.bento.habitBrickHint": "习惯砖块记录",
    "screens.statsNew.bento.habitCountLabel": "习惯次数",
    "screens.statsNew.bento.habitPageHint": "前往习惯页查看详情",
    "screens.statsNew.bento.habitStrengthBuilding": "正在建立",
    "screens.statsNew.bento.habitStrengthStable": "稳定期",
    "screens.statsNew.bento.habitStrengthStarting": "起步期",
    "screens.statsNew.bento.habitStrengthSuper": "卓越期",
    "screens.statsNew.bento.habitTracking": "习惯追踪",
    "screens.statsNew.bento.hourlyCompletionDistribution": "小时级完成分布",
    "screens.statsNew.bento.ignorePeriodCount": "期间忽略：{{count}}",
    "screens.statsNew.bento.ignoreRate": "忽略率",
    "screens.statsNew.bento.ignoreTitle": "忽略统计",
    "screens.statsNew.bento.ignoreTotal": "总计忽略：{{count}}",
    "screens.statsNew.bento.ignoredByTag": "按标签忽略",
    "screens.statsNew.bento.ignoredTasksCancelable": "可取消忽略的任务",
    "screens.statsNew.bento.last14DaysCompletion": "近14日完成情况",
    "screens.statsNew.bento.last30Days": "近30日",
    "screens.statsNew.bento.loading": "正在加载...",
    "screens.statsNew.bento.noFlowRecords": "暂无心流记录",
    "screens.statsNew.bento.noHabitsSubtitle": "开始添加你的第一个习惯吧",
    "screens.statsNew.bento.noHabitsTitle": "暂无追踪习惯",
    "screens.statsNew.bento.noIgnoredTasks": "暂无忽略的任务",
    "screens.statsNew.bento.peakHour": "高峰时段",
    "screens.statsNew.bento.peakHourLabel": "最高产的小时",
    "screens.statsNew.bento.plannedVsActualBlocks": "计划 vs 实际时段",
    "screens.statsNew.bento.procrastinationHigh": "高拖延",
    "screens.statsNew.bento.procrastinationIndex": "拖延指数",
    "screens.statsNew.bento.procrastinationLow": "低拖延",
    "screens.statsNew.bento.procrastinationMid": "中度拖延",
    "screens.statsNew.bento.procrastinationTendencyIndex": "拖延倾向指数",
    "screens.statsNew.bento.psychDisclaimer": "心理分析仅供参考",
    "screens.statsNew.bento.psychologyAnalysis": "心理学分析",
    "screens.statsNew.bento.psychologyReport": "心理分析报告",
    "screens.statsNew.bento.restore": "还原",
    "screens.statsNew.bento.screenTaskCrossInsights": "屏幕任务交叉洞察",
    "screens.statsNew.bento.statusAdjust": "需调整",
    "screens.statsNew.bento.statusGood": "状态良好",
    "screens.statsNew.bento.statusImprove": "可优化",
    "screens.statsNew.bento.streak": "连续天数",
    "screens.statsNew.bento.streak7DaysPlus": "连续 7 天以上",
    "screens.statsNew.bento.tapToGrantPermission": "点击授予权限",
    "screens.statsNew.bento.targetedImprovements": "针对性改进",
    "screens.statsNew.bento.timesPerWeek": "次/周",
    "screens.statsNew.bento.todayAppCategoryUsage": "今日 App 分类用时",
    "screens.statsNew.bento.todayDone": "今日已完成",
    "screens.statsNew.bento.todayTodo": "今日待办",
    "screens.statsNew.bento.unignoreHint": "点击取消忽略",
    "screens.statsNew.bento.unignoredSnack": "已取消忽略",
    "screens.statsNew.bento.usageAnalysis": "使用情况分析",
    "screens.statsNew.bento.usageAnalysisBeta": "使用分析 (Beta)",
    "screens.statsNew.bestVitality": "最佳活力",
    "screens.statsNew.completedTasks": "已完成任务",
    "screens.statsNew.completionDistribution": "完成分布",
    "screens.statsNew.completionRank": "完成排名",
    "screens.statsNew.completionRateByBlock": "时段完成率",
    "screens.statsNew.completionTitle": "完成统计",
    "screens.statsNew.dailyCompletion": "每日完成",
    "screens.statsNew.dailyFocusDuration": "每日专注时长",
    "screens.statsNew.dateFormat": "{{year}}年{{month}}月{{day}}日",
    "screens.statsNew.dayOfYear": "第{{day}}天 (第{{week}}周)",
    "screens.statsNew.deviation": "偏差",
    "screens.statsNew.evening": "晚上",
    "screens.statsNew.focus": "专注",
    "screens.statsNew.focusStats": "专注统计",
    "screens.statsNew.monthFormat": "{{year}}年{{month}}月",
    "screens.statsNew.morning": "早晨",
    "screens.statsNew.noData": "暂无数据",
    "screens.statsNew.noDeviationData": "暂无偏差数据",
    "screens.statsNew.noise.assess.loud": "喧闹",
    "screens.statsNew.noise.assess.moderate": "适中",
    "screens.statsNew.noise.assess.quiet": "安静",
    "screens.statsNew.noise.assess.silent": "极静",
    "screens.statsNew.noise.assess.veryLoud": "极吵",
    "screens.statsNew.noise.avgDbDashLabel": "平均分贝",
    "screens.statsNew.noise.avgDbLabel": "平均分贝",
    "screens.statsNew.noise.bestFocusTime": "最佳专注时段",
    "screens.statsNew.noise.envFocus30Days": "近30日环境专注",
    "screens.statsNew.noise.envGood": "环境优良",
    "screens.statsNew.noise.envNoisy": "环境嘈杂",
    "screens.statsNew.noise.envScoreSummary": "环境得分概览",
    "screens.statsNew.noise.history": "历史记录",
    "screens.statsNew.noise.latestDb": "最新分贝",
    "screens.statsNew.noise.level.loud": "嘈杂",
    "screens.statsNew.noise.level.moderate": "适中",
    "screens.statsNew.noise.level.quiet": "安静",
    "screens.statsNew.noise.level.silent": "静谧",
    "screens.statsNew.noise.level.veryLoud": "刺耳",
    "screens.statsNew.noise.manualMeasure": "手动测量",
    "screens.statsNew.noise.noHistory": "暂无历史数据",
    "screens.statsNew.noise.personalAdvice": "个人建议",
    "screens.statsNew.noise.pomSampling": "番茄钟采样",
    "screens.statsNew.noise.pomTrend": "番茄钟趋势",
    "screens.statsNew.noise.recording": "正在录音...",
    "screens.statsNew.noise.samplesLine": "采样点",
    "screens.statsNew.noise.secondsProgress": "秒进度",
    "screens.statsNew.noise.singleSession": "单次会话",
    "screens.statsNew.noise.start30s": "开始 30s 采样",
    "screens.statsNew.noise.suggestBasedOnMedian": "基于中位数建议",
    "screens.statsNew.noise.suggestFocusMins": "建议专注时长",
    "screens.statsNew.noise.tapRecordHint": "点击开始环境测量",
    "screens.statsNew.noise.tapToRecord": "点击测量",
    "screens.statsNew.noise.title": "环境声检测",
    "screens.statsNew.noise.waiting": "等待中...",
    "screens.statsNew.noise.yModerate": "适中",
    "screens.statsNew.noise.yNoisy": "嘈杂",
    "screens.statsNew.noise.yQuiet": "安静",
    "screens.statsNew.onTime": "准时",
    "screens.statsNew.overallAdvanced": "总体提前",
    "screens.statsNew.overallDelayed": "总体延后",
    "screens.statsNew.periodAdded": "期间新增",
    "screens.statsNew.periodCompleted": "期间完成",
    "screens.statsNew.periodCompletion": "期间完成情况",
    "screens.statsNew.periodFocus": "期间专注时长",
    "screens.statsNew.plannedVsActual": "计划 vs 实际",
    "screens.statsNew.semesterWeek": "学期周次",
    "screens.statsNew.share": "分享",
    "screens.statsNew.tagCompletion": "标签完成情况",
    "screens.statsNew.tagDetails": "标签详情",
    "screens.statsNew.tagFocusRank": "标签专注排名",
    "screens.statsNew.tagStats": "标签统计",
    "screens.statsNew.tagStatsHeader": "标签统计概览",
    "screens.statsNew.tagTotalCompletion": "标签总完成数",
    "screens.statsNew.timeBlockDistribution": "时段分布",
    "screens.statsNew.totalCompleted": "总完成数",
    "screens.statsNew.totalFocus": "总专注时长",
    "screens.statsNew.vitalitySummary": "活力概览",
    "screens.statsNew.weekFormat": "{{year}}年第{{week}}周",
    "screens.statsNew.weekRange": "周范围",
    "screens.statsNew.yearFormat": "{{year}}年",
    "screens.today.noTasks": "今日无任务",
    "screens.today.presets.beige": "米白",
    "screens.today.presets.darkBlue": "深蓝",
    "screens.today.presets.darkGray": "深灰",
    "screens.today.presets.darkGreen": "深绿",
    "screens.today.presets.lightBlue": "浅蓝",
    "screens.today.presets.lightGreen": "浅绿",
    "screens.today.presets.lightPink": "浅粉",
    "screens.today.presets.lightPurple": "浅紫",
    "screens.today.presets.limestone": "石灰",
    "screens.today.presets.warmWhite": "暖白",
    "screens.today.smartPlan.psych.cognitiveInsight.burstStall": "爆发停滞型",
    "screens.today.smartPlan.psych.cognitiveInsight.fluctuating": "波动型",
    "screens.today.smartPlan.psych.cognitiveInsight.lowStart": "起步慢型",
    "screens.today.smartPlan.psych.cognitiveInsight.stable": "稳健型",
    "screens.today.smartPlan.psych.deepFocus.insufficientInsight": "专注度不足洞察",
    "screens.today.smartPlan.psych.ignoreRateInsight": "忽略率洞察",
    "screens.today.smartPlan.psych.procrastination.highInsight": "高拖延预警",
    "screens.today.smartPlan.psych.procrastination.lowInsight": "执行力极佳",
    "screens.today.smartPlan.psych.procrastination.midInsight": "中度拖延提示",
    "screens.today.smartPlan.psych.recommendations.alignWithGoals": "对齐长期目标",
    "screens.today.smartPlan.psych.recommendations.minExecutionBaseline": "最低执行基准",
    "screens.today.smartPlan.psych.recommendations.scheduleHardInPeak": "高峰期排难项",
    "screens.today.smartPlan.psych.recommendations.singleTaskFocus": "单任务专注",
    "screens.today.smartPlan.psych.recommendations.splitOverdue": "拆解逾期项",
    "screens.today.smartPlan.psych.recommendations.twoMinuteRule": "两分钟法则",
    "screens.today.smartPlan.psych.selfEfficacy.low": "效能感偏低",
    "screens.today.todayFocus": "今日专注",
    "time.hourMinute": "{{hour}}时{{minute}}分"
  };

  Map<String, String> enMap = {
    "blocks.afternoon.color": "Afternoon Color",
    "blocks.afternoon.emoji": "☀️",
    "blocks.afternoon.name": "Afternoon",
    "blocks.evening.color": "Evening Color",
    "blocks.evening.emoji": "🌙",
    "blocks.evening.name": "Evening",
    "blocks.morning.color": "Morning Color",
    "blocks.morning.emoji": "🌅",
    "blocks.morning.name": "Morning",
    "common.cancel": "Cancel",
    "common.dayToday": "Today",
    "common.dayTomorrow": "Tomorrow",
    "common.ignore": "Ignore",
    "common.save": "Save",
    "greeting": "Hello",
    "screens.pomodoro.bindTask": "Bind Task",
    "screens.pomodoro.currentPhase": "Current Phase",
    "screens.pomodoro.cycle": "Cycle",
    "screens.pomodoro.cycleUnit": "times",
    "screens.pomodoro.focus": "Focus",
    "screens.pomodoro.longBreak": "Long Break",
    "screens.pomodoro.nextPhase": "Next Phase",
    "screens.pomodoro.noTask": "No Task",
    "screens.pomodoro.pause": "Pause",
    "screens.pomodoro.reset": "Reset",
    "screens.pomodoro.resume": "Resume",
    "screens.pomodoro.shortBreak": "Short Break",
    "screens.pomodoro.skip": "Skip",
    "screens.pomodoro.start": "Start",
    "screens.settings.appNameLbl": "App Name",
    "screens.settings.applyThemeWithName": "Apply Theme: {{name}}",
    "screens.settings.changeWallpaper": "Change Wallpaper",
    "screens.settings.colorModeTip": "Color Mode Tip",
    "screens.settings.colorThresh": "Color Threshold",
    "screens.settings.completed": "Completed",
    "screens.settings.current": "Current",
    "screens.settings.currentPreview": "Current Preview",
    "screens.settings.customAppCategories": "Custom Categories",
    "screens.settings.customBgImage": "Custom Background",
    "screens.settings.customBgImageHint": "Tap to upload background",
    "screens.settings.customCategoriesSet": "Custom categories set",
    "screens.settings.defaultStatsViewSubtitle": "Default view on stats page",
    "screens.settings.defaultView": "Default View",
    "screens.settings.disposable": "Disposable Time",
    "screens.settings.festivalCalendarHint": "Show Festival Calendar",
    "screens.settings.globalAppearance": "Global Appearance",
    "screens.settings.globalBgColor": "Global Background",
    "screens.settings.globalBgColorHintImage": "Wallpaper Opacity",
    "screens.settings.globalBgColorHintNoImage": "Background Color",
    "screens.settings.globalOpacityHintImage": "Global Opacity (with Image)",
    "screens.settings.globalOpacityHintNoImage": "Global Opacity",
    "screens.settings.installDate": "Install Date",
    "screens.settings.logs.action": "Action",
    "screens.settings.logs.all": "All Logs",
    "screens.settings.logs.clearConfirmContent": "Are you sure to clear all logs?",
    "screens.settings.logs.clearConfirmTitle": "Clear Logs",
    "screens.settings.logs.clearLogs": "Clear",
    "screens.settings.logs.copiedOne": "One log copied",
    "screens.settings.logs.copyReport": "Copy Report",
    "screens.settings.logs.copySuccess": "Copied!",
    "screens.settings.logs.emptyNoLogs": "No logs yet",
    "screens.settings.logs.emptyNoMatch": "No matching logs",
    "screens.settings.logs.entriesCount": "{{count}} entries",
    "screens.settings.logs.error": "Error",
    "screens.settings.logs.exportShare": "Export & Share",
    "screens.settings.logs.fatal": "Fatal",
    "screens.settings.logs.info": "Info",
    "screens.settings.logs.searchHint": "Search logs...",
    "screens.settings.logs.shareFailed": "Share failed",
    "screens.settings.logs.sortNewestFirst": "Newest First",
    "screens.settings.logs.sortOldestFirst": "Oldest First",
    "screens.settings.logs.summaryAction": "Action",
    "screens.settings.logs.summaryError": "Error",
    "screens.settings.logs.summaryTotal": "Total",
    "screens.settings.logs.summaryWarn": "Warn",
    "screens.settings.logs.title": "Diagnostic Logs",
    "screens.settings.logs.warn": "Warn",
    "screens.settings.longPresEdit": "Long press to edit",
    "screens.settings.monthlyReport": "Monthly Report",
    "screens.settings.monthlyReportSubject": "Mindless Monthly Report",
    "screens.settings.monthlyReportSubtitle": "Generated on the 1st of each month",
    "screens.settings.moreExportOptions": "More Export Options",
    "screens.settings.moreExportOptionsDesc": "Export to JSON, CSV etc.",
    "screens.settings.openingGallery": "Opening Gallery...",
    "screens.settings.rate": "Rate Us",
    "screens.settings.restoreDefaultBg": "Restore Default Background",
    "screens.settings.semSettings": "Semester Settings",
    "screens.settings.showPomodoro": "Show Pomodoro",
    "screens.settings.tagMgmt": "Tag Management",
    "screens.settings.topChromeOpacityHint": "Status bar opacity",
    "screens.settings.topChromeOpacityTitle": "Top Opacity",
    "screens.settings.total": "Total",
    "screens.settings.uploadWallpaper": "Upload Wallpaper",
    "screens.settings.wallpaperModeTip": "Wallpaper mode tip",
    "screens.settings.wallpaperUploadHint": "Tap to upload new wallpaper",
    "screens.settings.weeklyReport": "Weekly Report",
    "screens.settings.weeklyReportSubject": "Mindless Weekly Report",
    "screens.settings.weeklyReportSubtitle": "Generated every Monday",
    "screens.stats.actual": "Actual",
    "screens.stats.actualDoneCount": "Actual Done: {{count}}",
    "screens.stats.afternoon": "Afternoon",
    "screens.stats.alphaLabel": "Alpha",
    "screens.stats.countLabel": "Count",
    "screens.stats.day": "Day",
    "screens.stats.deviationDesc": "Analysis of estimated vs actual time",
    "screens.stats.deviationTitle": "Deviation",
    "screens.stats.evening": "Evening",
    "screens.stats.morning": "Morning",
    "screens.stats.noData": "No Data",
    "screens.stats.onTimeRate": "On-time Rate",
    "screens.stats.planned": "Planned",
    "screens.stats.plannedCount": "Planned: {{count}}",
    "screens.stats.rankLabel": "Rank",
    "screens.stats.timeLabel": "Time",
    "screens.stats.vitalityTitle": "Vitality",
    "screens.statsNew.afternoon": "Afternoon",
    "screens.statsNew.bento.appUsageDuration": "App Usage",
    "screens.statsNew.bento.behavioralInsights": "Behavioral Insights",
    "screens.statsNew.bento.categoryGame": "Games",
    "screens.statsNew.bento.categoryLegendItem": "Category Legend",
    "screens.statsNew.bento.categoryMusic": "Music",
    "screens.statsNew.bento.categoryNews": "News",
    "screens.statsNew.bento.categorySocial": "Social",
    "screens.statsNew.bento.categoryVideo": "Video",
    "screens.statsNew.bento.categoryWork": "Work",
    "screens.statsNew.bento.cognitivePattern": "Cognitive Pattern",
    "screens.statsNew.bento.completionTime": "Completion Time",
    "screens.statsNew.bento.completionTimeDistribution": "Time Distribution",
    "screens.statsNew.bento.createdAt": "Created at",
    "screens.statsNew.bento.deviationAhead": "Ahead",
    "screens.statsNew.bento.deviationDelayed": "Delayed",
    "screens.statsNew.bento.deviationNoData": "No Data",
    "screens.statsNew.bento.deviationOnTime": "On-time",
    "screens.statsNew.bento.efficiencyHealthIndex": "Efficiency Index",
    "screens.statsNew.bento.estimateDeviation": "Estimate Deviation",
    "screens.statsNew.bento.flowAutoRecordedHint": "Flow auto-recorded by Pomodoro",
    "screens.statsNew.bento.flowCompletePomHint": "Complete Pomodoro for Flow records",
    "screens.statsNew.bento.flowImproveTitle": "How to improve Flow?",
    "screens.statsNew.bento.flowScoreUnit": "pts",
    "screens.statsNew.bento.flowTip1Body": "Match challenge with skills",
    "screens.statsNew.bento.flowTip1Title": "Balance Challenge",
    "screens.statsNew.bento.flowTip2Body": "Minimize distractions",
    "screens.statsNew.bento.flowTip2Title": "Control Env",
    "screens.statsNew.bento.flowTip3Body": "Set clear objectives",
    "screens.statsNew.bento.flowTip3Title": "Clear Goals",
    "screens.statsNew.bento.flowTip4Body": "Focus on immediate feedback",
    "screens.statsNew.bento.flowTip4Title": "Immediate Feedback",
    "screens.statsNew.bento.flowTrend30Days": "Flow Trend (30d)",
    "screens.statsNew.bento.flowWhatIsBody": "Flow is a state of total immersion",
    "screens.statsNew.bento.flowWhatIsTitle": "What is Flow?",
    "screens.statsNew.bento.focusEntertainmentSummary": "Focus vs Entertainment",
    "screens.statsNew.bento.habitBrickHint": "Habit Bricks",
    "screens.statsNew.bento.habitCountLabel": "Habit Count",
    "screens.statsNew.bento.habitPageHint": "Go to Habits page for details",
    "screens.statsNew.bento.habitStrengthBuilding": "Building",
    "screens.statsNew.bento.habitStrengthStable": "Stable",
    "screens.statsNew.bento.habitStrengthStarting": "Starting",
    "screens.statsNew.bento.habitStrengthSuper": "Elite",
    "screens.statsNew.bento.habitTracking": "Habit Tracking",
    "screens.statsNew.bento.hourlyCompletionDistribution": "Hourly Distribution",
    "screens.statsNew.bento.ignorePeriodCount": "Ignored in period: {{count}}",
    "screens.statsNew.bento.ignoreRate": "Ignore Rate",
    "screens.statsNew.bento.ignoreTitle": "Ignore Stats",
    "screens.statsNew.bento.ignoreTotal": "Total ignored: {{count}}",
    "screens.statsNew.bento.ignoredByTag": "Ignored by Tag",
    "screens.statsNew.bento.ignoredTasksCancelable": "Cancelable ignored tasks",
    "screens.statsNew.bento.last14DaysCompletion": "Last 14 days completion",
    "screens.statsNew.bento.last30Days": "Last 30 days",
    "screens.statsNew.bento.loading": "Loading...",
    "screens.statsNew.bento.noFlowRecords": "No flow records",
    "screens.statsNew.bento.noHabitsSubtitle": "Start adding your first habit",
    "screens.statsNew.bento.noHabitsTitle": "No habits tracked",
    "screens.statsNew.bento.noIgnoredTasks": "No ignored tasks",
    "screens.statsNew.bento.peakHour": "Peak Hour",
    "screens.statsNew.bento.peakHourLabel": "Most productive hour",
    "screens.statsNew.bento.plannedVsActualBlocks": "Planned vs Actual",
    "screens.statsNew.bento.procrastinationHigh": "High",
    "screens.statsNew.bento.procrastinationIndex": "Procrastination Index",
    "screens.statsNew.bento.procrastinationLow": "Low",
    "screens.statsNew.bento.procrastinationMid": "Moderate",
    "screens.statsNew.bento.procrastinationTendencyIndex": "Tendency Index",
    "screens.statsNew.bento.psychDisclaimer": "For reference only",
    "screens.statsNew.bento.psychologyAnalysis": "Psych Analysis",
    "screens.statsNew.bento.psychologyReport": "Psych Report",
    "screens.statsNew.bento.restore": "Restore",
    "screens.statsNew.bento.screenTaskCrossInsights": "Cross Insights",
    "screens.statsNew.bento.statusAdjust": "Need Adjust",
    "screens.statsNew.bento.statusGood": "Good",
    "screens.statsNew.bento.statusImprove": "Optimizable",
    "screens.statsNew.bento.streak": "Streak",
    "screens.statsNew.bento.streak7DaysPlus": "7+ days streak",
    "screens.statsNew.bento.tapToGrantPermission": "Tap to grant permission",
    "screens.statsNew.bento.targetedImprovements": "Targeted Improvements",
    "screens.statsNew.bento.timesPerWeek": "times/week",
    "screens.statsNew.bento.todayAppCategoryUsage": "App Category Usage",
    "screens.statsNew.bento.todayDone": "Done Today",
    "screens.statsNew.bento.todayTodo": "Todo Today",
    "screens.statsNew.bento.unignoreHint": "Tap to unignore",
    "screens.statsNew.bento.unignoredSnack": "Unignored",
    "screens.statsNew.bento.usageAnalysis": "Usage Analysis",
    "screens.statsNew.bento.usageAnalysisBeta": "Usage Analysis (Beta)",
    "screens.statsNew.bestVitality": "Best Vitality",
    "screens.statsNew.completedTasks": "Completed Tasks",
    "screens.statsNew.completionDistribution": "Completion Distribution",
    "screens.statsNew.completionRank": "Completion Rank",
    "screens.statsNew.completionRateByBlock": "Rate by Block",
    "screens.statsNew.completionTitle": "Completion Stats",
    "screens.statsNew.dailyCompletion": "Daily Completion",
    "screens.statsNew.dailyFocusDuration": "Daily Focus",
    "screens.statsNew.dateFormat": "{{month}}/{{day}}/{{year}}",
    "screens.statsNew.dayOfYear": "Day {{day}} (Week {{week}})",
    "screens.statsNew.deviation": "Deviation",
    "screens.statsNew.evening": "Evening",
    "screens.statsNew.focus": "Focus",
    "screens.statsNew.focusStats": "Focus Stats",
    "screens.statsNew.monthFormat": "{{month}}/{{year}}",
    "screens.statsNew.morning": "Morning",
    "screens.statsNew.noData": "No Data",
    "screens.statsNew.noDeviationData": "No Deviation Data",
    "screens.statsNew.noise.assess.loud": "Loud",
    "screens.statsNew.noise.assess.moderate": "Moderate",
    "screens.statsNew.noise.assess.quiet": "Quiet",
    "screens.statsNew.noise.assess.silent": "Silent",
    "screens.statsNew.noise.assess.veryLoud": "Very Loud",
    "screens.statsNew.noise.avgDbDashLabel": "Avg dB",
    "screens.statsNew.noise.avgDbLabel": "Avg dB",
    "screens.statsNew.noise.bestFocusTime": "Best Focus Time",
    "screens.statsNew.noise.envFocus30Days": "Env Focus (30d)",
    "screens.statsNew.noise.envGood": "Good Env",
    "screens.statsNew.noise.envNoisy": "Noisy Env",
    "screens.statsNew.noise.envScoreSummary": "Env Score Summary",
    "screens.statsNew.noise.history": "History",
    "screens.statsNew.noise.latestDb": "Latest dB",
    "screens.statsNew.noise.level.loud": "Noisy",
    "screens.statsNew.noise.level.moderate": "Moderate",
    "screens.statsNew.noise.level.quiet": "Quiet",
    "screens.statsNew.noise.level.silent": "Silent",
    "screens.statsNew.noise.level.veryLoud": "Extreme",
    "screens.statsNew.noise.manualMeasure": "Manual Measure",
    "screens.statsNew.noise.noHistory": "No history yet",
    "screens.statsNew.noise.personalAdvice": "Personal Advice",
    "screens.statsNew.noise.pomSampling": "Pom Sampling",
    "screens.statsNew.noise.pomTrend": "Pom Trend",
    "screens.statsNew.noise.recording": "Recording...",
    "screens.statsNew.noise.samplesLine": "Samples",
    "screens.statsNew.noise.secondsProgress": "s Progress",
    "screens.statsNew.noise.singleSession": "Single Session",
    "screens.statsNew.noise.start30s": "Start 30s Sample",
    "screens.statsNew.noise.suggestBasedOnMedian": "Suggest by Median",
    "screens.statsNew.noise.suggestFocusMins": "Suggest Focus (mins)",
    "screens.statsNew.noise.tapRecordHint": "Tap to start measuring",
    "screens.statsNew.noise.tapToRecord": "Tap to measure",
    "screens.statsNew.noise.title": "Noise Detection",
    "screens.statsNew.noise.waiting": "Waiting...",
    "screens.statsNew.noise.yModerate": "Moderate",
    "screens.statsNew.noise.yNoisy": "Noisy",
    "screens.statsNew.noise.yQuiet": "Quiet",
    "screens.statsNew.onTime": "On-time",
    "screens.statsNew.overallAdvanced": "Overall Advanced",
    "screens.statsNew.overallDelayed": "Overall Delayed",
    "screens.statsNew.periodAdded": "Added in Period",
    "screens.statsNew.periodCompleted": "Completed in Period",
    "screens.statsNew.periodCompletion": "Period Completion",
    "screens.statsNew.periodFocus": "Period Focus",
    "screens.statsNew.plannedVsActual": "Planned vs Actual",
    "screens.statsNew.semesterWeek": "Semester Week",
    "screens.statsNew.share": "Share",
    "screens.statsNew.tagCompletion": "Tag Completion",
    "screens.statsNew.tagDetails": "Tag Details",
    "screens.statsNew.tagFocusRank": "Tag Focus Rank",
    "screens.statsNew.tagStats": "Tag Stats",
    "screens.statsNew.tagStatsHeader": "Tag Stats Summary",
    "screens.statsNew.tagTotalCompletion": "Tag Total Done",
    "screens.statsNew.timeBlockDistribution": "Block Distribution",
    "screens.statsNew.totalCompleted": "Total Completed",
    "screens.statsNew.totalFocus": "Total Focus",
    "screens.statsNew.vitalitySummary": "Vitality Summary",
    "screens.statsNew.weekFormat": "Week {{week}}, {{year}}",
    "screens.statsNew.weekRange": "Week Range",
    "screens.statsNew.yearFormat": "{{year}}",
    "screens.today.noTasks": "No tasks today",
    "screens.today.presets.beige": "Beige",
    "screens.today.presets.darkBlue": "Dark Blue",
    "screens.today.presets.darkGray": "Dark Gray",
    "screens.today.presets.darkGreen": "Dark Green",
    "screens.today.presets.lightBlue": "Light Blue",
    "screens.today.presets.lightGreen": "Light Green",
    "screens.today.presets.lightPink": "Light Pink",
    "screens.today.presets.lightPurple": "Light Purple",
    "screens.today.presets.limestone": "Limestone",
    "screens.today.presets.warmWhite": "Warm White",
    "screens.today.smartPlan.psych.cognitiveInsight.burstStall": "Burst-Stall",
    "screens.today.smartPlan.psych.cognitiveInsight.fluctuating": "Fluctuating",
    "screens.today.smartPlan.psych.cognitiveInsight.lowStart": "Low-Start",
    "screens.today.smartPlan.psych.cognitiveInsight.stable": "Stable",
    "screens.today.smartPlan.psych.deepFocus.insufficientInsight": "Focus Insight",
    "screens.today.smartPlan.psych.ignoreRateInsight": "Ignore Rate Insight",
    "screens.today.smartPlan.psych.procrastination.highInsight": "High Procrastination Alert",
    "screens.today.smartPlan.psych.procrastination.lowInsight": "Great Execution",
    "screens.today.smartPlan.psych.procrastination.midInsight": "Moderate Procrastination",
    "screens.today.smartPlan.psych.recommendations.alignWithGoals": "Align with goals",
    "screens.today.smartPlan.psych.recommendations.minExecutionBaseline": "Min baseline",
    "screens.today.smartPlan.psych.recommendations.scheduleHardInPeak": "Hard tasks in peak",
    "screens.today.smartPlan.psych.recommendations.singleTaskFocus": "Single task focus",
    "screens.today.smartPlan.psych.recommendations.splitOverdue": "Split overdue",
    "screens.today.smartPlan.psych.recommendations.twoMinuteRule": "2-minute rule",
    "screens.today.smartPlan.psych.selfEfficacy.low": "Low self-efficacy",
    "screens.today.todayFocus": "Today's Focus",
    "time.hourMinute": "{{hour}}h {{minute}}m"
  };

  void inject(File file, Map<String, String> translations) {
    final data = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    translations.forEach((key, value) {
      final keys = key.split('.');
      Map<String, dynamic> current = data;
      for (int i = 0; i < keys.length - 1; i++) {
        current = current.putIfAbsent(keys[i], () => <String, dynamic>{});
      }
      current[keys.last] = value;
    });
    file.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(data));
  }

  inject(zhFile, zhMap);
  inject(enFile, enMap);
  print('✅ Injected ${zhMap.length} keys into zh.json and en.json');
}
